services:
  audio-listener:
    build: ./backend
    container_name: noise_listener
    restart: unless-stopped
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./data:/app/data

  dashboard:
    build: ./frontend
    container_name: noise_dashboard
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
